apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialmedia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socialmedia
  template:
    metadata:
      labels:
        app: socialmedia
    spec:
      containers:
      - name: socialmedia
        image: australia-southeast2-docker.pkg.dev/deakin-sit725/sit725/socialmedia:adhishanand
        ports:
        - containerPort: 3003

---

apiVersion: v1
kind: Service
metadata:
  name: socialmedia
spec:
  selector:
    app: socialmedia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: LoadBalancer
 
